import { createElement } from 'lwc';
import OtherComponents from 'c/otherComponents';

describe('c-other-components', () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it('TODO: test case generated by CLI command, please fill in test logic', () => {
    // Arrange
    const element = createElement('c-other-components', {
      is: OtherComponents
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // Test will not reach this code if the <thunder-hammer-button> is not mocked up in Jest
    expect(1).toBe(1);
  });
});
